"""Event types emitted by the fundamental agent contract."""

from enum import StrEnum


class AgentEventType(StrEnum):
    """Identify a stable lifecycle event represented by an agent event."""

    EXECUTION_CREATED = "execution_created"
    EXECUTION_STARTED = "execution_started"
    EXECUTION_STATUS_CHANGED = "execution_status_changed"
    INPUT_VALIDATION_STARTED = "input_validation_started"
    INPUT_VALIDATION_COMPLETED = "input_validation_completed"
    CONTEXT_LOADING_STARTED = "context_loading_started"
    CONTEXT_LOADING_COMPLETED = "context_loading_completed"
    KNOWLEDGE_RETRIEVAL_STARTED = "knowledge_retrieval_started"
    KNOWLEDGE_RETRIEVAL_COMPLETED = "knowledge_retrieval_completed"
    MODEL_EXECUTION_STARTED = "model_execution_started"
    MODEL_EXECUTION_COMPLETED = "model_execution_completed"
    MODEL_STREAM_STARTED = "model_stream_started"
    MODEL_TEXT_DELTA = "model_text_delta"
    MODEL_TOOL_CALL_STARTED = "model_tool_call_started"
    MODEL_TOOL_CALL_ARGUMENT_DELTA = "model_tool_call_argument_delta"
    MODEL_TOOL_CALL_COMPLETED = "model_tool_call_completed"
    MODEL_USAGE_UPDATED = "model_usage_updated"
    MODEL_STREAM_COMPLETED = "model_stream_completed"
    TOOL_REQUESTED = "tool_requested"
    TOOL_EXECUTION_STARTED = "tool_execution_started"
    TOOL_EXECUTION_COMPLETED = "tool_execution_completed"
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_RESOLVED = "approval_resolved"
    APPROVAL_REQUESTED = "approval_requested"
    APPROVAL_GRANTED = "approval_granted"
    APPROVAL_REJECTED = "approval_rejected"
    EXECUTION_SUSPENDED = "execution_suspended"
    EXECUTION_RESUMED = "execution_resumed"
    OUTPUT_VALIDATION_STARTED = "output_validation_started"
    OUTPUT_VALIDATION_COMPLETED = "output_validation_completed"
    MEMORY_UPDATE_STARTED = "memory_update_started"
    MEMORY_UPDATE_COMPLETED = "memory_update_completed"
    EXECUTION_COMPLETED = "execution_completed"
    EXECUTION_FAILED = "execution_failed"
    EXECUTION_CANCELLED = "execution_cancelled"
    EXECUTION_TIMED_OUT = "execution_timed_out"
    EXECUTION_LIMIT_EXCEEDED = "execution_limit_exceeded"
    EXECUTION_BUDGET_EXCEEDED = "execution_budget_exceeded"
    EXECUTION_REJECTED = "execution_rejected"
