"""External transport adapters over one application execution facade."""

from atlas_agents.adapters._version import __version__
from atlas_agents.adapters.errors import (
    AdapterConfigurationError,
    AdapterError,
    AdapterSerializationError,
    AdapterStreamingError,
    AdapterUnavailableError,
    AgentAccessDeniedError,
    AgentNotRegisteredError,
    DuplicateAgentError,
    IdempotencyConflictError,
    IdentityMappingError,
    InvalidExternalRequestError,
)
from atlas_agents.adapters.idempotency import (
    IdempotencyRecord,
    IdempotencyState,
    IdempotencyStore,
    InMemoryIdempotencyStore,
)
from atlas_agents.adapters.models import (
    AdapterErrorResponse,
    AdapterExecutionStatus,
    ApprovalRequestDTO,
    CitationDTO,
    ExecuteAgentRequest,
    ExecuteAgentResponse,
    ExecutionStreamItem,
    ExecutionSuspensionDTO,
    ExternalAgentInput,
    ExternalAttachment,
    ExternalExecutionContext,
    ReadinessResponse,
    RequestedExecutionBudget,
    RequestedExecutionLimits,
    ResumeExecutionRequest,
    TransportPrincipal,
    UsageDTO,
)
from atlas_agents.adapters.optional import MissingAdapterDependencyError
from atlas_agents.adapters.policies import (
    AgentAccessPolicy,
    AgentOperation,
    AllowAllAgentAccessPolicy,
    BoundedExecutionPolicyResolver,
    EffectiveExecutionPolicy,
    ExecutionIdentityMapper,
    ExecutionPolicyResolver,
    SubjectExecutionIdentityMapper,
)
from atlas_agents.adapters.registry import AgentRegistry
from atlas_agents.adapters.service import (
    AgentExecutionService,
    AgentRegistryPort,
    AgentRuntimePort,
)

__all__ = [
    "AdapterConfigurationError",
    "AdapterError",
    "AdapterErrorResponse",
    "AdapterExecutionStatus",
    "AdapterSerializationError",
    "AdapterStreamingError",
    "AdapterUnavailableError",
    "AgentAccessDeniedError",
    "AgentAccessPolicy",
    "AgentExecutionService",
    "AgentNotRegisteredError",
    "AgentOperation",
    "AgentRegistry",
    "AgentRegistryPort",
    "AgentRuntimePort",
    "AllowAllAgentAccessPolicy",
    "ApprovalRequestDTO",
    "BoundedExecutionPolicyResolver",
    "CitationDTO",
    "DuplicateAgentError",
    "EffectiveExecutionPolicy",
    "ExecuteAgentRequest",
    "ExecuteAgentResponse",
    "ExecutionIdentityMapper",
    "ExecutionPolicyResolver",
    "ExecutionStreamItem",
    "ExecutionSuspensionDTO",
    "ExternalAgentInput",
    "ExternalAttachment",
    "ExternalExecutionContext",
    "IdempotencyConflictError",
    "IdempotencyRecord",
    "IdempotencyState",
    "IdempotencyStore",
    "IdentityMappingError",
    "InMemoryIdempotencyStore",
    "InvalidExternalRequestError",
    "MissingAdapterDependencyError",
    "ReadinessResponse",
    "RequestedExecutionBudget",
    "RequestedExecutionLimits",
    "ResumeExecutionRequest",
    "SubjectExecutionIdentityMapper",
    "TransportPrincipal",
    "UsageDTO",
    "__version__",
]
