"""Optional provider-neutral Model Context Protocol integration."""

from atlas_agents.mcp.client import MCPClient, MCPClientConfig
from atlas_agents.mcp.errors import (
    MCPAuthenticationError,
    MCPAuthorizationError,
    MCPCapabilityError,
    MCPClientNotConnectedError,
    MCPConfigurationError,
    MCPConnectionError,
    MCPError,
    MCPInputRequiredUnsupportedError,
    MCPMappingError,
    MCPPromptError,
    MCPProtocolError,
    MCPResourceError,
    MCPResourceTooLargeError,
    MCPToolError,
    MCPTransportError,
    MCPVersionError,
)
from atlas_agents.mcp.models import (
    MCPClientState,
    MCPContent,
    MCPEmbeddedResourceContent,
    MCPImageContent,
    MCPPromptArgument,
    MCPPromptDescriptor,
    MCPPromptMessage,
    MCPPromptProvider,
    MCPPromptResult,
    MCPResourceContent,
    MCPResourceDescriptor,
    MCPResourceProvider,
    MCPResourceTemplateDescriptor,
    MCPServerCapability,
    MCPServerInfo,
    MCPTextContent,
    MCPToolDescriptor,
    MCPToolResult,
    MCPTransportType,
)
from atlas_agents.mcp.server import (
    AnonymousMCPToolExecutionContextFactory,
    AtlasMCPServer,
    MCPServerConfig,
    MCPToolExecutionContextFactory,
)
from atlas_agents.mcp.tools import (
    MCPRemoteTool,
    MCPToolImporter,
    MCPToolNamingPolicy,
)
from atlas_agents.mcp.transports import (
    MCPTransport,
    StdioMCPTransport,
    StdioMCPTransportConfig,
    StreamableHTTPMCPTransport,
    StreamableHTTPMCPTransportConfig,
)

MCP_PROTOCOL_BASELINE = "2026-07-28"

__all__ = [
    "MCP_PROTOCOL_BASELINE",
    "AnonymousMCPToolExecutionContextFactory",
    "AtlasMCPServer",
    "MCPAuthenticationError",
    "MCPAuthorizationError",
    "MCPCapabilityError",
    "MCPClient",
    "MCPClientConfig",
    "MCPClientNotConnectedError",
    "MCPClientState",
    "MCPConfigurationError",
    "MCPConnectionError",
    "MCPContent",
    "MCPEmbeddedResourceContent",
    "MCPError",
    "MCPImageContent",
    "MCPInputRequiredUnsupportedError",
    "MCPMappingError",
    "MCPPromptArgument",
    "MCPPromptDescriptor",
    "MCPPromptError",
    "MCPPromptMessage",
    "MCPPromptProvider",
    "MCPPromptResult",
    "MCPProtocolError",
    "MCPRemoteTool",
    "MCPResourceContent",
    "MCPResourceDescriptor",
    "MCPResourceError",
    "MCPResourceProvider",
    "MCPResourceTemplateDescriptor",
    "MCPResourceTooLargeError",
    "MCPServerCapability",
    "MCPServerConfig",
    "MCPServerInfo",
    "MCPTextContent",
    "MCPToolDescriptor",
    "MCPToolError",
    "MCPToolExecutionContextFactory",
    "MCPToolImporter",
    "MCPToolNamingPolicy",
    "MCPToolResult",
    "MCPTransport",
    "MCPTransportError",
    "MCPTransportType",
    "MCPVersionError",
    "StdioMCPTransport",
    "StdioMCPTransportConfig",
    "StreamableHTTPMCPTransport",
    "StreamableHTTPMCPTransportConfig",
]
