"""Public plugin discovery, authoring, and lifecycle API."""

from atlas_agents.plugins.contract import Plugin
from atlas_agents.plugins.contributions import (
    EvaluatorContribution,
    EvaluatorExtension,
    GuardrailContribution,
    KnowledgeRetrieverContribution,
    MemoryStoreContribution,
    ModelProviderContribution,
    ObservabilityContribution,
    PluginContribution,
    PluginContributionDescriptor,
    PluginContributionValue,
    ToolContribution,
)
from atlas_agents.plugins.discovery import (
    PLUGIN_ENTRY_POINT_GROUP,
    PluginDiscovery,
    PluginEntryPoint,
    PluginLoader,
    PluginLoadResult,
)
from atlas_agents.plugins.errors import (
    DuplicatePluginError,
    PluginActivationError,
    PluginAlreadyActiveError,
    PluginCompatibilityError,
    PluginContractError,
    PluginContributionConflictError,
    PluginDeactivationError,
    PluginDiscoveryError,
    PluginError,
    PluginErrorInfo,
    PluginLoadError,
    PluginManifestError,
    PluginNotActiveError,
    PluginNotFoundError,
    PluginProtocolError,
    PluginRegistrationError,
    PluginRegistryError,
    PluginRollbackError,
)
from atlas_agents.plugins.manager import EvaluatorRegistryLike, PluginManager
from atlas_agents.plugins.manifest import (
    PluginCapability,
    PluginCompatibilityChecker,
    PluginContext,
    PluginManifest,
    PluginMetadata,
)
from atlas_agents.plugins.registry import PluginRegistry
from atlas_agents.plugins.results import PluginActivationResult, PluginInfo

__all__ = [
    "PLUGIN_ENTRY_POINT_GROUP",
    "DuplicatePluginError",
    "EvaluatorContribution",
    "EvaluatorExtension",
    "EvaluatorRegistryLike",
    "GuardrailContribution",
    "KnowledgeRetrieverContribution",
    "MemoryStoreContribution",
    "ModelProviderContribution",
    "ObservabilityContribution",
    "Plugin",
    "PluginActivationError",
    "PluginActivationResult",
    "PluginAlreadyActiveError",
    "PluginCapability",
    "PluginCompatibilityChecker",
    "PluginCompatibilityError",
    "PluginContext",
    "PluginContractError",
    "PluginContribution",
    "PluginContributionConflictError",
    "PluginContributionDescriptor",
    "PluginContributionValue",
    "PluginDeactivationError",
    "PluginDiscovery",
    "PluginDiscoveryError",
    "PluginEntryPoint",
    "PluginError",
    "PluginErrorInfo",
    "PluginInfo",
    "PluginLoadError",
    "PluginLoadResult",
    "PluginLoader",
    "PluginManager",
    "PluginManifest",
    "PluginManifestError",
    "PluginMetadata",
    "PluginNotActiveError",
    "PluginNotFoundError",
    "PluginProtocolError",
    "PluginRegistrationError",
    "PluginRegistry",
    "PluginRegistryError",
    "PluginRollbackError",
    "ToolContribution",
]
