"""Declarative, strict, and optional Atlas composition APIs."""

from atlas_agents.config.composition import (
    AtlasComposition,
    AtlasCompositionBuilder,
    ExternalExecutionDependencies,
    RuntimeDependencies,
    configuration_fingerprint,
)
from atlas_agents.config.errors import (
    ComponentBuildError,
    ComponentFactoryNotFoundError,
    CompositionBuildError,
    CompositionCloseError,
    ConfigError,
    ConfigOverrideError,
    ConfigParseError,
    ConfigReferenceError,
    ConfigSecurityError,
    ConfigValidationError,
    DuplicateComponentConfigError,
    DuplicateFactoryError,
    FactoryRegistryError,
    SecretResolutionError,
    UnsupportedConfigVersionError,
)
from atlas_agents.config.factories import (
    AdapterBuildContext,
    AdapterFactory,
    ConfigurationBuildContext,
    ExternalAdapter,
    FactoryProduct,
    GuardrailFactory,
    KnowledgeFactory,
    MCPBuildContext,
    MCPFactory,
    MCPIntegration,
    MemoryFactory,
    ModelProviderFactory,
    ObservabilityFactory,
    OwnedResource,
    ToolFactory,
)
from atlas_agents.config.loader import load_config, load_json, load_yaml
from atlas_agents.config.models import (
    AdapterComponentConfig,
    AgentConfig,
    AgentGuardrailConfig,
    AgentKnowledgeConfig,
    AgentMemoryConfig,
    AgentModelConfig,
    AtlasConfig,
    AtlasRuntimeConfig,
    ComponentConfig,
    ConfigValue,
    ExecutionBudgetConfig,
    ExecutionLimitsConfig,
    KnowledgeComponentConfig,
    MCPComponentConfig,
    MCPToolImportConfig,
    PluginConfig,
)
from atlas_agents.config.overrides import merge_config_overrides
from atlas_agents.config.registry import ConfigurationFactoryRegistry
from atlas_agents.config.result import (
    ConfigIssueSeverity,
    ConfigValidationIssue,
    ConfigValidationResult,
)
from atlas_agents.config.secrets import (
    MappingSecretResolver,
    RejectingSecretResolver,
    SecretReference,
    SecretResolver,
    SecretValue,
)
from atlas_agents.config.validation import ConfigurationValidator, validate_config_file
from atlas_agents.config.versioning import (
    CURRENT_CONFIG_SCHEMA_VERSION,
    SUPPORTED_CONFIG_SCHEMA_VERSIONS,
)

__all__ = [
    "CURRENT_CONFIG_SCHEMA_VERSION",
    "SUPPORTED_CONFIG_SCHEMA_VERSIONS",
    "AdapterBuildContext",
    "AdapterComponentConfig",
    "AdapterFactory",
    "AgentConfig",
    "AgentGuardrailConfig",
    "AgentKnowledgeConfig",
    "AgentMemoryConfig",
    "AgentModelConfig",
    "AtlasComposition",
    "AtlasCompositionBuilder",
    "AtlasConfig",
    "AtlasRuntimeConfig",
    "ComponentBuildError",
    "ComponentConfig",
    "ComponentFactoryNotFoundError",
    "CompositionBuildError",
    "CompositionCloseError",
    "ConfigError",
    "ConfigIssueSeverity",
    "ConfigOverrideError",
    "ConfigParseError",
    "ConfigReferenceError",
    "ConfigSecurityError",
    "ConfigValidationError",
    "ConfigValidationIssue",
    "ConfigValidationResult",
    "ConfigValue",
    "ConfigurationBuildContext",
    "ConfigurationFactoryRegistry",
    "ConfigurationValidator",
    "DuplicateComponentConfigError",
    "DuplicateFactoryError",
    "ExecutionBudgetConfig",
    "ExecutionLimitsConfig",
    "ExternalAdapter",
    "ExternalExecutionDependencies",
    "FactoryProduct",
    "FactoryRegistryError",
    "GuardrailFactory",
    "KnowledgeComponentConfig",
    "KnowledgeFactory",
    "MCPBuildContext",
    "MCPComponentConfig",
    "MCPFactory",
    "MCPIntegration",
    "MCPToolImportConfig",
    "MappingSecretResolver",
    "MemoryFactory",
    "ModelProviderFactory",
    "ObservabilityFactory",
    "OwnedResource",
    "PluginConfig",
    "RejectingSecretResolver",
    "RuntimeDependencies",
    "SecretReference",
    "SecretResolutionError",
    "SecretResolver",
    "SecretValue",
    "ToolFactory",
    "UnsupportedConfigVersionError",
    "configuration_fingerprint",
    "load_config",
    "load_json",
    "load_yaml",
    "merge_config_overrides",
    "validate_config_file",
]
