"""Provider-agnostic primitives for building and running AI agents."""

from importlib.metadata import version as _distribution_version

from atlas_agents.agents import (
    Agent,
    AgentAttachment,
    AgentContext,
    AgentDefinition,
    AgentErrorInfo,
    AgentInput,
    AgentResult,
    ExecutionIdentity,
    ExecutionStatus,
    Usage,
)
from atlas_agents.events import AgentEvent, AgentEventFactory, AgentEventType
from atlas_agents.exceptions import (
    AtlasAgentError,
    InvalidExecutionTransitionError,
    ModelAuthenticationError,
    ModelInvalidRequestError,
    ModelNotFoundError,
    ModelPermissionError,
    ModelProviderError,
    ModelRateLimitError,
    ModelResponseError,
    ModelTimeoutError,
    ModelUnavailableError,
)
from atlas_agents.execution import ExecutionLifecycle, ExecutionTransition, is_terminal
from atlas_agents.models import (
    AudioContent,
    FinishReason,
    ImageContent,
    MessageContent,
    MessageRole,
    ModelCapability,
    ModelDescriptor,
    ModelExecutionContext,
    ModelMessage,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    ModelStreamEvent,
    ModelStreamEventType,
    ModelToolDefinition,
    ModelUsage,
    StructuredOutputDefinition,
    TextContent,
    ToolCall,
)

__version__: str = _distribution_version("atlas-agent-core")

__all__ = [
    "Agent",
    "AgentAttachment",
    "AgentContext",
    "AgentDefinition",
    "AgentErrorInfo",
    "AgentEvent",
    "AgentEventFactory",
    "AgentEventType",
    "AgentInput",
    "AgentResult",
    "AtlasAgentError",
    "AudioContent",
    "ExecutionIdentity",
    "ExecutionLifecycle",
    "ExecutionStatus",
    "ExecutionTransition",
    "FinishReason",
    "ImageContent",
    "InvalidExecutionTransitionError",
    "MessageContent",
    "MessageRole",
    "ModelAuthenticationError",
    "ModelCapability",
    "ModelDescriptor",
    "ModelExecutionContext",
    "ModelInvalidRequestError",
    "ModelMessage",
    "ModelNotFoundError",
    "ModelPermissionError",
    "ModelProvider",
    "ModelProviderError",
    "ModelRateLimitError",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseError",
    "ModelStreamEvent",
    "ModelStreamEventType",
    "ModelTimeoutError",
    "ModelToolDefinition",
    "ModelUnavailableError",
    "ModelUsage",
    "StructuredOutputDefinition",
    "TextContent",
    "ToolCall",
    "Usage",
    "__version__",
    "is_terminal",
]
