# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from atlas_agents.adapters.grpc.v1 import agent_execution_pb2 as atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atlas_agents/adapters/grpc/v1/agent_execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentExecutionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/atlas.agent.v1.AgentExecutionService/Execute',
                request_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/atlas.agent.v1.AgentExecutionService/Stream',
                request_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/atlas.agent.v1.AgentExecutionService/Resume',
                request_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.SerializeToString,
                response_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ResumeStream = channel.unary_stream(
                '/atlas.agent.v1.AgentExecutionService/ResumeStream',
                request_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.SerializeToString,
                response_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.FromString,
                _registered_method=True)


class AgentExecutionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.FromString,
                    response_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.FromString,
                    response_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.FromString,
                    response_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.SerializeToString,
            ),
            'ResumeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ResumeStream,
                    request_deserializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.FromString,
                    response_serializer=atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atlas.agent.v1.AgentExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atlas.agent.v1.AgentExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentExecutionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.agent.v1.AgentExecutionService/Execute',
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.SerializeToString,
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/atlas.agent.v1.AgentExecutionService/Stream',
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteRequest.SerializeToString,
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.agent.v1.AgentExecutionService/Resume',
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.SerializeToString,
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/atlas.agent.v1.AgentExecutionService/ResumeStream',
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.ResumeRequest.SerializeToString,
            atlas__agents_dot_adapters_dot_grpc_dot_v1_dot_agent__execution__pb2.StreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
